export const CHEERS_DATA: Record<string, string> = {
  "Afganistan": "Pa de kher",
  "Almanya": "Prost",
  "Amerika Birleşik Devletleri": "Cheers",
  "Andorra": "Salut",
  "Angola": "Saúde",
  "Antigua ve Barbuda": "Cheers",
  "Arjantin": "Salud",
  "Arnavutluk": "Gëzuar",
  "Avustralya": "Cheers",
  "Avusturya": "Prost",
  "Azerbaycan": "Nuş olsun!",
  "Bahamalar": "Cheers",
  "Bahreyn": "Fi sihtik",
  "Bangladeş": "Joy",
  "Barbados": "Cheers",
  "Belçika": "Proost",
  "Belize": "Cheers",
  "Benin": "Santé",
  "Bhutan": "Gyu gyu",
  "Birleşik Arap Emirlikleri": "Fi sihtik",
  "Birleşik Krallık": "Cheers",
  "Bolivya": "Kawsaypa",
  "Bosna Hersek": "Živjeli",
  "Botsvana": "Pula",
  "Brezilya": "Saúde",
  "Brunei": "Cheers",
  "Bulgaristan": "Nazdrave",
  "Burkina Faso": "Santé",
  "Burundi": "Santé",
  "Cezayir": "Saha",
  "Cibuti": "Santé",
  "Çad": "Saha",
  "Çek Cumhuriyeti": "Na zdraví",
  "Çin": "Gānbēi",
  "Danimarka": "Skål",
  "Doğu Timor": "Saúde",
  "Dominika": "Cheers",
  "Dominik Cumhuriyeti": "Salud",
  "Ekvador": "Kawsaypa",
  "Ekvator Ginesi": "Salud",
  "El Salvador": "Salud",
  "Endonezya": "Prost",
  "Eritre": "Sahtain",
  "Ermenistan": "Genatzt",
  "Estonya": "Terviseks",
  "Esvatini": "Cheers",
  "Etiyopya": "L'tenachin",
  "Fas": "Bssaha",
  "Fiji": "Bula",
  "Fildişi Sahili": "Santé",
  "Filipinler": "Tagay",
  "Filistin": "Fi sihtik",
  "Finlandiya": "Kippis",
  "Fransa": "Santé",
  "Gabon": "Santé",
  "Gambiya": "Cheers",
  "Gana": "Akwaaba",
  "Gine": "Santé",
  "Gine-Bissau": "Saúde",
  "Grenada": "Cheers",
  "Guatemala": "Salud",
  "Guyana": "Proost",
  "Güney Afrika": "Gesondheid",
  "Güney Kıbrıs": "Yamas",
  "Güney Kore": "Geonbae",
  "Güney Sudan": "Fi sihtik",
  "Gürcistan": "Gaumarjos!",
  "Haiti": "Ochan",
  "Hırvatistan": "Živjeli",
  "Hindistan": "Chakh De",
  "Hollanda": "Proost",
  "Honduras": "Salud",
  "Irak": "Fi sihtik",
  "İran": "Ba salamati",
  "İrlanda": "Sláinte",
  "İspanya": "Salud",
  "İsrail": "L'chaim",
  "İsveç": "Skål",
  "İsviçre": "Prost",
  "İtalya": "Salute",
  "İzlanda": "Skål",
  "Jamaika": "Cheers",
  "Japonya": "Kanpai",
  "Kamboçya": "Choul mouy",
  "Kamerun": "Santé",
  "Kanada": "Cheers",
  "Karadağ": "Živjeli",
  "Katar": "Fi sihtik",
  "Kazakistan": "Densawlığıñız üşin",
  "Kenya": "Maisha marefu!",
  "Kırgızistan": "Den-sooluk üchün",
  "Kiribati": "Mauri",
  "Kolombiya": "Salud",
  "Komorlar": "Santé",
  "Kongo Cumhuriyeti": "Santé",
  "Kongo Demokratik Cumhuriyeti": "Santé",
  "Kosta Rika": "Pura vida",
  "Kuveyt": "Fi sihtik",
  "Kuzey Kıbrıs Türk Cumhuriyeti": "Şerefe",
  "Kuzey Kore": "Chukbae",
  "Kuzey Makedonya": "Na zdravje",
  "Küba": "Salud",
  "Laos": "Tam de",
  "Lesotho": "Cheers",
  "Letonya": "Uz veselību",
  "Liberya": "Cheers",
  "Libya": "Saha",
  "Liechtenstein": "Prost",
  "Litvanya": "Į sveikatą",
  "Lübnan": "Fi sahetak",
  "Lüksemburg": "Prost",
  "Macaristan": "Egészségedre",
  "Madagaskar": "Ho fahasalamana",
  "Malavi": "Moni",
  "Maldivler": "Ufauveri hifumek",
  "Malezya": "Yum seng",
  "Mali": "Santé",
  "Malta": "Evviva",
  "Marshall Adaları": "Yokwe",
  "Mauritius": "Cheers",
  "Meksika": "Salud",
  "Mısır": "Fi sihatik",
  "Mikronezya": "Cheers",
  "Moğolistan": "Togtoo",
  "Moldova": "Noroc",
  "Monako": "Santé",
  "Moritanya": "Saha",
  "Mozambik": "Saúde",
  "Myanmar": "Aung myin par say",
  "Namibya": "Prost",
  "Nauru": "Cheers",
  "Nepal": "Shuva kamana",
  "Nijer": "Santé",
  "Nijerya": "Mma mma nụ",
  "Nikaragua": "Salud",
  "Niue": "Cheers",
  "Norveç": "Skål",
  "Orta Afrika Cumhuriyeti": "Santé",
  "Özbekistan": "Salomat bo'ling",
  "Pakistan": "Salami",
  "Palau": "Cheers",
  "Panama": "Salud",
  "Papua Yeni Gine": "Cheers",
  "Paraguay": "Vy'apave",
  "Peru": "Kawsaypa",
  "Polonya": "Na zdravie",
  "Portekiz": "Saúde",
  "Romanya": "Noroc",
  "Ruanda": "Turye",
  "Rusya": "Za Zdorovye",
  "Saint Kitts ve Nevis": "Cheers",
  "Saint Lucia": "Cheers",
  "Saint Vincent ve Grenadinler": "Cheers",
  "Samoa": "Manuia",
  "San Marino": "Salute",
  "Sao Tome ve Principe": "Saúde",
  "Senegal": "Santé",
  "Seyşeller": "Santé",
  "Sırbistan": "Živjeli",
  "Sierra Leone": "Cheers",
  "Singapur": "Yum seng",
  "Slovakya": "Na zdravie",
  "Slovenya": "Na zdravje",
  "Solomon Adaları": "Cheers",
  "Somali": "Mahadsanid",
  "Sri Lanka": "Sira",
  "Sudan": "Fi sihtik",
  "Surinam": "Proost",
  "Suriye": "Fi sihtik",
  "Suudi Arabistan": "Fi sihtik",
  "Şili": "Salud",
  "Tacikistan": "Ba salomati",
  "Tanzanya": "Maisha marefu!",
  "Tayland": "Chok di",
  "Tayvan": "Hō-la",
  "Togo": "Santé",
  "Tonga": "Malo e lele",
  "Trinidad ve Tobago": "Cheers",
  "Tunus": "Saha",
  "Tuvalu": "Cheers",
  "Türkiye": "Şerefe",
  "Türkmenistan": "Jan sağlığı",
  "Uganda": "Bulamu",
  "Ukrayna": "Budmo",
  "Umman": "Fi sihtik",
  "Uruguay": "Salud",
  "Ürdün": "Sahtain",
  "Vanuatu": "Salud",
  "Vatikan": "Bene tibi",
  "Venezuela": "Salud",
  "Vietnam": "Một, hai, ba, dô",
  "Yemen": "Fi sihtik",
  "Yeni Zelanda": "Kia ora",
  "Yunanistan": "Yamas",
  "Zambiya": "Cheers",
  "Zimbabve": "Cheers"
};

export const COUNTRY_TR_NAMES: Record<string, string> = {
  "United States of America": "Amerika Birleşik Devletleri",
  "Canada": "Kanada",
  "Mexico": "Meksika",
  "Brazil": "Brezilya",
  "Argentina": "Arjantin",
  "Peru": "Peru",
  "Colombia": "Kolombiya",
  "Chile": "Şili",
  "United Kingdom": "Birleşik Krallık",
  "Germany": "Almanya",
  "France": "Fransa",
  "Italy": "İtalya",
  "Spain": "İspanya",
  "Netherlands": "Hollanda",
  "Sweden": "İsveç",
  "Switzerland": "İsviçre",
  "Poland": "Polonya",
  "Turkey": "Türkiye",
  "Japan": "Japonya",
  "China": "Çin",
  "India": "Hindistan",
  "Singapore": "Singapur",
  "South Korea": "Güney Kore",
  "Vietnam": "Vietnam",
  "Taiwan": "Tayvan",
  "Greece": "Yunanistan",
  "Israel": "İsrail",
  "Saudi Arabia": "Suudi Arabistan",
  "United Arab Emirates": "Birleşik Arap Emirlikleri",
  "South Africa": "Güney Afrika",
  "Egypt": "Mısır",
  "Nigeria": "Nijerya",
  "Australia": "Avustralya",
  "New Zealand": "Yeni Zelanda",
  "Russia": "Rusya",
  "Afghanistan": "Afganistan",
  "Albania": "Arnavutluk",
  "Algeria": "Cezayir",
  "Andorra": "Andorra",
  "Angola": "Angola",
  "Antarctica": "Antarktika",
  "Armenia": "Ermenistan",
  "Austria": "Avusturya",
  "Azerbaijan": "Azerbaycan",
  "The Bahamas": "Bahamalar",
  "Bahrain": "Bahreyn",
  "Bangladesh": "Bangladeş",
  "Barbados": "Barbados",
  "Belarus": "Belarus",
  "Belgium": "Belçika",
  "Belize": "Belize",
  "Benin": "Benin",
  "Bhutan": "Bhutan",
  "Bolivia": "Bolivya",
  "Bosnia and Herzegovina": "Bosna Hersek",
  "Botswana": "Botsvana",
  "Bulgaria": "Bulgaristan",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cambodia": "Kamboçya",
  "Cameroon": "Kamerun",
  "Central African Republic": "Orta Afrika Cumhuriyeti",
  "Chad": "Çad",
  "Costa Rica": "Kosta Rika",
  "Croatia": "Hırvatistan",
  "Cuba": "Küba",
  "Cyprus": "Güney Kıbrıs",
  "Czechia": "Çek Cumhuriyeti",
  "Democratic Republic of the Congo": "Kongo Demokratik Cumhuriyeti",
  "Denmark": "Danimarka",
  "Djibouti": "Cibuti",
  "Dominican Republic": "Dominik Cumhuriyeti",
  "Ecuador": "Ekvador",
  "El Salvador": "El Salvador",
  "Equatorial Guinea": "Ekvator Ginesi",
  "Eritrea": "Eritre",
  "Estonia": "Estonya",
  "Ethiopia": "Etiyopya",
  "Fiji": "Fiji",
  "Finland": "Finlandiya",
  "Gabon": "Gabon",
  "Gambia": "Gambiya",
  "Georgia": "Gürcistan",
  "Ghana": "Gana",
  "Guatemala": "Guatemala",
  "Guinea": "Gine",
  "Guinea Bissau": "Gine-Bissau",
  "Guyana": "Guyana",
  "Haiti": "Haiti",
  "Honduras": "Honduras",
  "Hungary": "Macaristan",
  "Iceland": "İzlanda",
  "Indonesia": "Endonezya",
  "Iran": "İran",
  "Iraq": "Irak",
  "Ireland": "İrlanda",
  "Ivory Coast": "Fildişi Sahili",
  "Jamaica": "Jamaika",
  "Jordan": "Ürdün",
  "Kazakhstan": "Kazakistan",
  "Kenya": "Kenya",
  "Kosovo": "Kosova",
  "Kuwait": "Kuveyt",
  "Kyrgyzstan": "Kırgızistan",
  "Laos": "Laos",
  "Latvia": "Letonya",
  "Lebanon": "Lübnan",
  "Lesotho": "Lesotho",
  "Liberia": "Liberya",
  "Libya": "Libya",
  "Lithuania": "Litvanya",
  "Luxembourg": "Lüksemburg",
  "Macedonia": "Kuzey Makedonya",
  "Madagascar": "Madagaskar",
  "Malawi": "Malavi",
  "Malaysia": "Malezya",
  "Mali": "Mali",
  "Mauritania": "Moritanya",
  "Moldova": "Moldova",
  "Mongolia": "Moğolistan",
  "Montenegro": "Karadağ",
  "Morocco": "Fas",
  "Mozambique": "Mozambik",
  "Myanmar": "Myanmar",
  "Namibia": "Namibya",
  "Nepal": "Nepal",
  "Nicaragua": "Nikaragua",
  "Niger": "Nijer",
  "North Korea": "Kuzey Kore",
  "Norway": "Norveç",
  "Oman": "Umman",
  "Pakistan": "Pakistan",
  "Palestine": "Filistin",
  "Panama": "Panama",
  "Papua New Guinea": "Papua Yeni Gine",
  "Paraguay": "Paraguay",
  "Philippines": "Filipinler",
  "Portugal": "Portekiz",
  "Puerto Rico": "Porto Riko",
  "Qatar": "Katar",
  "Republic of Serbia": "Sırbistan",
  "Republic of the Congo": "Kongo Cumhuriyeti",
  "Romania": "Romanya",
  "Rwanda": "Ruanda",
  "Senegal": "Senegal",
  "Sierra Leone": "Sierra Leone",
  "Slovakia": "Slovakya",
  "Slovenia": "Slovenya",
  "Somalia": "Somali",
  "Somaliland": "Somaliland",
  "South Sudan": "Güney Sudan",
  "Sri Lanka": "Sri Lanka",
  "Sudan": "Sudan",
  "Suriname": "Surinam",
  "Syria": "Suriye",
  "Tajikistan": "Tacikistan",
  "Thailand": "Tayland",
  "East Timor": "Doğu Timor",
  "Togo": "Togo",
  "Trinidad and Tobago": "Trinidad ve Tobago",
  "Tunisia": "Tunus",
  "Turkmenistan": "Türkmenistan",
  "Uganda": "Uganda",
  "Ukraine": "Ukrayna",
  "United Republic of Tanzania": "Tanzanya",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Özbekistan",
  "Vanuatu": "Vanuatu",
  "Venezuela": "Venezuela",
  "Western Sahara": "Batı Sahra",
  "Yemen": "Yemen",
  "Zambia": "Zambiya",
  "Zimbabwe": "Zimbabve",
  "Swaziland": "Esvatini",
  "United States": "Amerika Birleşik Devletleri",
  "Northern Cyprus": "Kuzey Kıbrıs Türk Cumhuriyeti",
};

export function getCheersForCountry(adminName: string): { trName: string, cheers: string } {
  const trName = COUNTRY_TR_NAMES[adminName] || adminName;
  const cheers = CHEERS_DATA[trName] || CHEERS_DATA[adminName] || "Cheers";
  return { trName, cheers };
}
