// Mapping of country names (or common variations) to their "Cheers" phrase
export const CHEERS_DATA: Record<string, string> = {
  // Europe
  "Germany": "Prost",
  "Austria": "Prost",
  "France": "Santé",
  "Italy": "Salute",
  "Spain": "Salud",
  "Mexico": "Salud",
  "Greece": "Yamas",
  "Russia": "Za Zdorovye",
  "Poland": "Na zdrowie",
  "Sweden": "Skål",
  "Norway": "Skål",
  "Denmark": "Skål",
  "Iceland": "Skål",
  "Ireland": "Sláinte",
  "Netherlands": "Proost",
  "United Kingdom": "Cheers",
  "United States": "Cheers",
  "United States of America": "Cheers",
  "Turkiye": "Şerefe",
  "Hungary": "Egészségedre",
  "Romania": "Noroc",
  "Croatia": "Živjeli",
  "Serbia": "Živjeli",
  "Bosnia and Herzegovina": "Živjeli",
  "Albania": "Gëzuar",
  "Slovakia": "Na zdravie",
  "Ukraine": "Budmo",
  "Czechia": "Na zdraví",
  "Czech Republic": "Na zdraví",
  "Slovenia": "Na zdravje",
  "Latvia": "Uz veselību",
  "Lithuania": "Į sveikatą",
  "Finland": "Kippis",
  "Estonia": "Terviseks",
  "Luxembourg": "Prost",
  "Malta": "Evviva",
  "Bulgaria": "Nazdrave",
  "Cyprus": "Stin iyia mas",
  "Moldova": "Noroc",
  "Monaco": "Santé",
  "San Marino": "Salute",
  
  // Asia & Pacific
  "Japan": "Kanpai",
  "China": "Gānbēi",
  "South Korea": "Geonbae",
  "North Korea": "Chukbae",
  "Thailand": "Chok di",
  "Vietnam": "Một, hai, ba, dô",
  "Philippines": "Tagay",
  "India": "Chakh De",
  "New Zealand": "Kia ora",
  "Kazakhstan": "Densawlığıñız üşin",
  "Mongolia": "Erööl makh",
  "Uzbekistan": "Salomat bo'ling",
  "Cambodia": "Choul mouy",
  "Malaysia": "Yum seng",
  "Singapore": "Yum Seng",
  "Taiwan": "Hō-la",
  "Laos": "Tam de",
  "Sri Lanka": "Sira",
  "Kyrgyzstan": "Den-sooluk üchün",
  "Tajikistan": "Ba salomati",
  "Afghanistan": "Pa de kher",
  "Bangladesh": "Joy",
  "Bhutan": "Gyu gyu",
  "Myanmar": "Aung myin par say",
  "Maldives": "Ufauveri hifumek",
  "Nepal": "Shuva kamana",
  "Pakistan": "Salami",
  "Papua New Guinea": "Cheers",
  "Fiji": "Bula",
  "Samoa": "Manuia",
  "Tonga": "Malo e lelei",

  // Middle East & Caucasus
  "Israel": "L'chaim",
  "Lebanon": "Fi sahetak",
  "Egypt": "Fi sihatik",
  "Georgia": "Gaumarjos!",
  "Armenia": "Genatzt",
  "Iran": "Ba salamati",
  "Azerbaijan": "Nuş olsun!",

  // Africa
  "South Africa": "Gesondheid",
  "Kenya": "Maisha marefu!",
  "Tanzania": "Maisha marefu!",
  "Nigeria": "Mma mma nụ",
  "Morocco": "Bssaha",
  "Ethiopia": "L'tenachin",
  "Angola": "Saúde",
  "Mozambique": "Saúde",
  "Botswana": "Pula",
  "Algeria": "Saha",
  "Tunisia": "Saha",
  "Ghana": "Akwaaba",
  "Madagascar": "Ho fahasalamana",
  "Rwanda": "Turye",
  "Uganda": "Bulamu",

  // Americas
  "Portugal": "Saúde",
  "Brazil": "Saúde",
  "Haiti": "Ochan",
  "Costa Rica": "Pura vida",
  "Greenland": "Kasugta",
  "Jamaica": "Cheers",
  "Bahamas": "Cheers",
  "Barbados": "Cheers",
  "Belize": "Cheers",
  "Bolivia": "Kawsaypa",
  "Ecuador": "Kawsaypa",
  "Peru": "Kawsaypa",
  "Guyana": "Proost",
  "Suriname": "Proost",
  "Paraguay": "Vy'apave",
  "Argentina": "Salud",
  "Chile": "Salud",
  "Colombia": "Salud",
  "Venezuela": "Salud",
  "Uruguay": "Salud",
  "Canada": "Cheers",
  "Australia": "Cheers"
};

export function getCheersForCountry(countryName: string): string | null {
  if (!countryName) return null;
  // Direct match
  if (CHEERS_DATA[countryName]) return CHEERS_DATA[countryName];
  
  // Try mapping common variations if needed, or return generic for known English speaking
  return null;
}
